# Generated by Django 4.2.1 on 2023-06-01 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('GPA', models.FloatField()),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(default='Active', max_length=8)),
                ('department', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=255)),
                ('mobilePhone', models.CharField(max_length=255)),
            ],
        ),
    ]
